import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Script from "next/script";
import Link from "next/link";

export default function Home() {
  return (
    <div className={styles.container}>
      <style jsx>
        {`
          h2 {
            font-size: 38px;
          }
        `}
      </style>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      

      <main className={styles.main}>
        <h1 className={styles.title}>
         Hunting Coder
        </h1>
      <div className={styles.imgWrap}>
      <Image className={styles.myImg} src='/homeImg.jpg' width={237} height={158}></Image>

      </div>
        <p className={styles.description}>
          A blog for Hunting coders by a Hunting Coder
        </p>

        <div>
            <h2 >Latest Blog</h2>
        <div className="blogs">
          <div className="blogItem">
            <h3>How to Learn JS In 2022</h3>
            <p>JavaScript is Language use to design a web</p>
          </div>
        </div>
        <div className="blogs">
          <div className="blogItem">
            <h3>How to Learn JS In 2022</h3>
            <p>JavaScript is Language use to design a web</p>
          </div>
        </div>
        <div className="blogs">
          <div className="blogItem">
            <h3>How to Learn JS In 2022</h3>
            <p>JavaScript is Language use to design a web</p>
          </div>
        </div>
        </div>
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}
